name: hw7env
dependencies:
  - python=3.9
  - ipykernel=6.7.0
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.3.5   
  - statsmodels=0.13.1
  - seaborn=0.11.2
  - scipy=1.7.3
  - tqdm=4.62.3
  - wquantiles=0.6
  - pytest

  - pip:
    - wquantiles
